### ISSUE TITLE
Add plated einsum example

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#10]
Add an example implementing plated einsum via funsors. Funsors are arguably a cleaner DSL for expressing these kinds of dynamic programs, and the example could demonstrate both how to implement general plated einsum, and how to express various specific problems using funsor syntax rather than einsum syntax.

## Outline
- [x] add a non-plated einsum example
- [x] add plated einsum implementation

**Comment by eb8680** [comment]
Even a completely naive working version of this will be really useful for testing

**Comment by eb8680** [comment]
Addressed by #46
