### ISSUE TITLE
Memoize doesn't work correctly as a handler?

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#14]
`Memoize` was recently made the non-default behavior and moved into `handlers.py`. However IIUC it cannot correctly be used as a handler:
1. it would always need to be at the top of the handler stack, i.e. be applied last
2. if any other handler is applied first, `Memoize` would not be called when constructing `Funsor` objects.

Am I missing something? I think we may want to simply move it back to being the default behavior (I cannot imagine a circumstance where we would not want to memoize).

**Comment by fritzo** [comment]
cc @eb8680

**Comment by fritzo** [comment]
Does `Memoize` work at the bottom of the `HANDLER_STACK` because any other handler simply calls a different constructor and that constructor would eventually hit `Memoize`?

**Comment by eb8680** [comment]
I don't see what's incorrect here - not all effects commute with each other, and that's OK.  We could always throw an error in `Memoize.__enter__` for now if it's not at the top of the stack.

> I cannot imagine a circumstance where we would not want to memoize

What about wanting to save memory in eager evaluation?  If there's a bug here, it's that `Memoize` may not support that correctly.

**Comment by fritzo** [comment]
Ok sounds reasonable. I was thinking of working around memory growth with a tensor method
```
def detach(self):
    return Tensor(self.dims, self.data.detach())
```
but sure I guess we could turn off memoization instead.
