### ISSUE TITLE
Unify multilinear operations

### ISSUE THREAD

**Issue by eb8680** [pyro-ppl/funsor#156]
Funsor currently contains many different representations of multilinear operations (e.g. `Joint`, `Affine`, `Finitary`, `Contract`, `Integrate`, `Binary`, `Reduce`, `einsum`, `sum_product`, ...) that approximately duplicate lots of logic and don't always play well together.

In a sequence of refactoring PRs, I would like to unify most of the duplicated linear algebra or normalization logic in the codebase while preserving all existing test cases and computational properties.  Specifically, I would like to:
1. #157 Add a `Contraction` normal form representing finitary sum-product operations with eager definitions implemented entirely in terms of unary and binary sum-product operations, and a `normalize` interpretation putting multilinear expressions into a DNF-like normal form
2. #157 Insert `normalize` as the underlying interpretation to which `eager` defaults, displacing `reflect` (optionally at first, using an environment variable as with the changes in #149).
3. #173 Remove `Affine` and replace with `Contraction` while preserving all existing test cases and functionality
4. #165 Simplify the optimizer by removing `Finitary`, `Contract`, `funsor.contract._simplify_contract`, and the `associate`, `distribute` and `desugar` interpretations used internally, and making it work with `normalize` and `Contraction`s directly
5. #169 Simplify `Integrate` by removing the duplicate functionality of `funsor.integrate._simplify_integrate`
6. #169 Remove `Joint` and replace with `Contraction` and `MultiDelta` while preserving all `Joint` test cases and computational properties.  This will also further simplify `eager`, since most of `Joint`'s functionality is already contained in the first PR.
7. #169 Remove `Delta` entirely in favor of `MultiDelta` so that deltas are closed under addition/logaddexp like `Gaussian` and `Tensor`
10. Troubleshoot performance issues related to interleaved interpreters (see `test_gaussian.py::test_eager_subs`, `test_samplers.py::test_gaussian_distribution`, `test_terms.py::test_reduce_subset` for cases of severe slowdowns)
8. Simplify `eager` by removing all purely algebraic computations from `eager` that are now handled by `normalize`, such as `funsor.terms.eager.distribute_binary_reduce_other`, and narrowing the focus of `eager` to only performing eager computations that actually invoke backend ops.
9. Rename `Contraction` -> `Contract`, `MultiDelta` -> `Empirical`, remove `Delta` entirely, move patterns in `joint.py` to `integrate.py`
11. Make optimization the default (merge `eager_contraction_generic_tuple` and the optimizer generic `Contraction` pattern from #165 )

More speculative: can we naturally and generically handle plate and scan dimensions #70 in `normalize`?

Plan for code review/merging:
1. Finish PRs for steps 1-6 above
2. Review and merge those PRs into #157, in descending order (i.e. 3, 4, 5, 6, 7)
3. Merge the final version of #157 into `master`
4. Make normalization the default and address steps 8-10 in cleanup PRs

Non-goals:
- I do not plan to replace or remove `Unary`, `Binary`, `Integrate`, or `Reduce`
- I do not plan to change any `eager` definitions or require them to be written in terms of `Contraction`.  `normalize` should not be proscriptive about the specification of eager operations.

**Comment by fritzo** [comment]
:100: this is a meticulous refactoring plan!
