### ISSUE TITLE
Should we drop Python 2 support?

### ISSUE THREAD

**Issue by eb8680** [pyro-ppl/funsor#158]
Now that Pyro is dropping Python 2 support (https://github.com/pyro-ppl/pyro/issues/1935), should we drop Python 2 in Funsor as well?

See Pyro checklist: https://github.com/pyro-ppl/pyro/issues/1963

**Comment by fritzo** [comment]
Yes. Unless you're in a hurry, I'd prefer to do this after we drop Python 2 support from Pyro, since we may learn things in doing that (e.g. like what to `sed` for).

**Comment by eb8680** [comment]
> Unless you're in a hurry

No rush, since we haven't released yet.  One potential reason to do this sooner is that we could start experimenting with adding Python 3 type annotations, but those may be unnecessary or may struggle with the amount of indirection in Funsor.

**Comment by eb8680** [comment]
Closing this as resolved by #172, reopen if necessary
