### ISSUE TITLE
Opt_einsum-based optimizer cannot handle Normal variable elimination

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#2]
One thing blocking the use of the opt_einsum-based optimizer for continuous variable elimination is that `Normal` currently implements only a limited contraction interface:
- `.reduce(ops.logaddexp, self.value)` which just returns `0 = log(1)` because it's normalized, and
- `.binary(ops.add, x)` where x is ground wrt the current contraction.

As a workaround we're using a `tree_engine` that performs Birch-style variable elimination on trees, starting from observations (leaves) and moving backwards. While this will work to demo the Kalman filter example, it is not a long-term solution.

## Possible fixes
- try to support more general `x` in `Normal.binary()`
- support direction hinting in the opt_einsum optimizer

**Comment by eb8680** [comment]
Thinking about this, our use case is different enough that it's probably easier to implement our own optimizer directly to begin with rather than attempting to use `opt_einsum.paths.greedy` or reuse some of their code.

**Comment by eb8680** [comment]
Mostly addressed by #37
