### ISSUE TITLE
optimize_reduce_binary_exp causes infinite loop

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#234]
The pattern [optimize_reduce_binary_exp](https://github.com/pyro-ppl/funsor/blob/ba03bdc/funsor/optimizer.py#L172) causes an infinite loop roughly
```
Integrate(...) -> prod_op(...).reduce(...) -> Integrate(...)
```
## To reproduce

Check out the BART example #228 and `make tinytest` (requires #232 )

**Comment by eb8680** [comment]
I've been having similar problems with Integrate, will try to find a
permanent solution.
