### ISSUE TITLE
Evaluate MatchPy as replacement for multipledispatch

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#239]
MatchPy is a term rewriting library that compiles matchers and handles associative-commutative-one rules.

https://github.com/HPAC/matchpy
https://arxiv.org/pdf/1710.00077.pdf

**Comment by eb8680** [comment]
I find it much easier to reason about multiple dispatch than a full pattern
matching / term rewriting system. Limiting the expressiveness of patterns
seems like a feature.
