### ISSUE TITLE
Support nontrivially shaped bint domains

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#322]
Motivation: this is required for e.g. `Independent(Categorical)` distributions and for `Function` tensors that input or output batched categoricals.

I believe this is a big change requiring pervasive updates to all shaping logic.

One design question is whether we allow heterogeneous bound as in e.g. heterogeneous Multionmial distributions. Maybe an initial version could implement homogeneous bound, then later a heterogeneous bound.

**Comment by fritzo** [comment]
We may want to separate `Bint` from `Reals`, then generalize `Reals` to `Array` with a `.dtype` property. Some reasons for separating `Bint` from `Array[int]` include:
1. Numpy [broadcasting semantics](https://numpy.org/neps/nep-0021-advanced-indexing.html) can behave differently for ints versus arrays
2. Tuple getitem naturally inputs `Bint` but not for arrays (indeed `Bint` can be seen as dual to `Tuple`)

**Comment by eb8680** [comment]
I'm going to close this as resolved by #417 and #356; if we need to implement specific patterns e.g. `Reduce` over nonscalar `Bint` domains for individual terms we can track them in separate issues.
