### ISSUE TITLE
Dependent in pytest

### ISSUE THREAD

**Issue by fehiepsi** [pyro-ppl/funsor#336]
Should we move `testing` to `test` and remove the dependent on `pytest`?

**Comment by fritzo** [comment]
IMO libraries should ship with testing utilities that simplify the writing of tests in higher level libraries. Why don't we see if these testing helpers end up being useful in downstream libraries like Pyro and NumPyro?

**Comment by fehiepsi** [comment]
Thanks, @fritzo! We just have minimal tests for `funsor` in NumPyro. I believe those utilities will be useful when the library grows up.
