### ISSUE TITLE
Docs are currently broken

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#343]
![image](https://user-images.githubusercontent.com/648532/88990240-5026ce00-d292-11ea-93fd-d0b1ef714315.png)

**Comment by fritzo** [comment]
@fehiepsi any idea what happened?

**Comment by fehiepsi** [comment]
I can generate docs in my system. From https://readthedocs.org/api/v2/build/11566158.txt, I think we missed `makefun` in docs requirements. But not sure if adding it is enough to resolve the issue.
