### ISSUE TITLE
examples/slds.py is broken

### ISSUE THREAD

**Issue by windweller** [pyro-ppl/funsor#359]
Hello! I git clone this repo and installed according to instruction.
Here's my dependencies:

```
pyro-ppl                                1.4.0
pyro-api                                0.1.2
torch                                     1.6.0
numpy                                   1.18.5
```

My Python version is 3.6. 

When I run `python examples/slds.py`, I get the following message:

```
Traceback (most recent call last):
  File "examples/slds.py", line 81, in <module>
    main(args)
  File "examples/slds.py", line 64, in main
    log_prob = model(data)
  File ".../miniconda3/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "examples/slds.py", line 42, in model
    log_prob += dist.Categorical(trans_probs[s_prev], value=s_curr)
  File ".../funsor/funsor/distribution.py", line 61, in __call__
    value = to_funsor(value, output=cls._infer_value_domain(**{k: v.output for k, v in kwargs.items()}))
  File ".../funsor/funsor/distribution.py", line 161, in _infer_value_domain
    validate_args=False)
  File "../miniconda3/lib/python3.6/site-packages/torch/distributions/categorical.py", line 48, in __init__
    if probs.dim() < 1:
AttributeError: 'numpy.ndarray' object has no attribute 'dim'
```

I tried other versions of Torch but doesn't seem to be fixing anything...

**Comment by eb8680** [comment]
Hi @windweller, you'll need to run this example under the `torch` backend. You can do that either by setting the `FUNSOR_BACKEND` environment variable (`FUNSOR_BACKEND=torch python examples/slds.py`) or by setting the backend in the code with `funsor.set_backend("torch")`.  Feel free to put up a PR with that fix!

**Comment by windweller** [comment]
Ah. Yup, this works :) Thanks!!

**Comment by fritzo** [comment]
@eb8680 this same problem confused me when I tried to run examples/vae.py. I think it's worth adding either a `funsor.set_backend("torch")` or `assert funsor.get_backend == "torch"` to all relevant examples. Do you have a preference?

**Comment by eb8680** [comment]
I'd prefer adding `funsor.set_backend("torch")`, so they work as expected.
