### ISSUE TITLE
Implement Beta-Binomial conjugacy

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#5]
We should be able to implement `Beta-Binomial` conjugacy via an operation `Beta.binary(ops.add, -)`.

## Outline

- [x] #120 Implement `Beta` and `Binomial` distributions
- [ ] Implement conjugacy relationship in `Joint.eager_reduce()`
- [ ] Add a Beta-Binomial example in examples

**Comment by fritzo** [comment]
@neerajprad this is a nice beginner task if you'd like to work on it, but no hurry 😄

**Comment by bogiebro** [comment]
Is this still being worked on? If not, I could give it a try. If Pyro's `BetaBinomial` were exposed, I could register a `Contraction` for `Beta` and `Binomial` over the Beta's value to produce a `BetaBinomial`. Then I'd register a `Binary` `SubOp` between the joint `Contraction[Beta,Binomial]` and `BetaBinomial` to produce the posterior `Beta`.

**Comment by fritzo** [comment]
@bogiebro go ahead, I believe nether @neerajprad nor I are working on this at the moment.

**Comment by bogiebro** [comment]
I have Dirichlet -Multinomial conjugacy working, but Beta-Binomial is a little tricky. The eager interpretation of a Beta is just to convert it to a Dirichlet (in `eager_beta` from `funsor/distribution.py:357`). This means I can't dispatch on Betas to take advantage of conjugacy: they vanish! I tried assembling the Beta and Bernoulli in a lazy interpretation before reducing them in an eager interpretation. This couldn't get around the problem, unfortunately. A Contraction's arguments get reinterpreted under eager mode  when the Contraction is interpreted under eager mode, so once again the Betas  get converted to Dirichlets. Perhaps this doesn't matter- if we have Dirichlet-Multinomial conjugacy, and Betas and Binomials get converted to Dirichlets and Multinomials automatically anyway, then we get conjugacy for Betas and Binomials for free. 

Shall I make a pull request for the Dirichlet Multinomial conjugacy?

**Comment by eb8680** [comment]
> Shall I make a pull request for the Dirichlet Multinomial conjugacy?

Sure, go ahead!
