### ISSUE TITLE
Increase test precision to float64?

### ISSUE THREAD

**Issue by fritzo** [pyro-ppl/funsor#573]
I'm seeing a lot of complex tests run out of precision, e.g. `atol=1e=3, rtol=1e-3`, where it becomes difficult to distinguish real errors from numerical imprecision. I think it might be worth switching the default dtypes for tests to float64.  This seems easy for `FUNSOR_BACKEND=torch`, but I'm unsure about numpy and jax.

@fehiepsi how difficult would it be to switch our CI tests to float64 for `FUNSOR_BACKEND=jax`?

**Comment by fehiepsi** [comment]
Hi @fritzo, I believe you can just add `JAX_ENABLE_x64=True` to each command in [this section](https://github.com/pyro-ppl/funsor/blob/master/Makefile#L55).

**Comment by fritzo** [comment]
Do you mean `JAX_ENABLE_X64`?  I'm confused about the case, after https://github.com/pyro-ppl/numpyro/pull/1188

**Comment by fehiepsi** [comment]
Oops, that is `JAX_ENALBE_X64` (`...x64` is a typo and has been fixed upstream in this pr https://github.com/google/jax/pull/1231).
