### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by GaetanLepage** [pyro-ppl/funsor#607]
Hello,
The tests from the following files fail.
```
test/examples/test_sensor_fusion.py
test/pyro/test_convert.py
test/pyro/test_distribution.py
test/pyro/test_hmm.py
test/pyroapi/test_pyroapi.py
```
You can find slightly more detailed `pytest` logs here: https://pastebin.com/J5SBPxZ7.

**Comment by ordabayevy** [comment]
Hi @GaetanLepage 

These tests past on my local machine with a fresh install of funsor. How did you run your tests?
Funsor supports multiple backends and some tests pass only with a specific backend. Can you run the tests using `make test` or have a look at a [Makefile](https://github.com/pyro-ppl/funsor/blob/ff5e410de720bc1f423f57cf156592fc194b058c/Makefile#L27) for those specific dependencies?

**Comment by fritzo** [comment]
@GaetanLepage Could you also provide the output of `python --version` and `pip freeze`?  BTW I find it useful to embed longform information in github markdown's `<details> ... </details>` tags like this:

<details>

```
long
form
information
here
```

</details>

**Comment by GaetanLepage** [comment]
Oh, I was not aware of the `Makefile`. Using the latter, everything works fine.
Thank you for the explanation, I guess that everything in all right now !
